# Generated by Django 5.0.6 on 2024-12-10 06:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Orthopedic', 'Orthopedic'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Radiologist', 'Radiologist')], max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('clinic_address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_doctor', models.BooleanField(default=True)),
                ('doctor_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('is_patient', models.BooleanField(default=True)),
                ('pat_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('clinic_name', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('recp_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Orthopedic', 'Orthopedic'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Radiologist', 'Radiologist')], max_length=100)),
                ('shifts', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=100, null=True)),
                ('day', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=9)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt_app.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'day', 'shifts', 'specialization')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('specialization', models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Cardiologist', 'Cardiologist'), ('Dermatologist', 'Dermatologist'), ('Neurologist', 'Neurologist'), ('Orthopedic', 'Orthopedic'), ('Pediatrician', 'Pediatrician'), ('Psychiatrist', 'Psychiatrist'), ('Radiologist', 'Radiologist')], max_length=100, null=True)),
                ('shift', models.CharField(max_length=40, null=True)),
                ('token', models.PositiveIntegerField(editable=False, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'doctor_user__role': 3}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to='clinic_mgt_app.doctor')),
                ('patient', models.ForeignKey(limit_choices_to={'pat_user__role': 4}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='clinic_mgt_app.patient')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt_app.schedule')),
            ],
            options={
                'unique_together': {('doctor', 'date', 'schedule', 'patient')},
            },
        ),
    ]
