# Generated by Django 5.1.2 on 2024-12-20 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt_app', '0004_medicine_test_dose'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_day', models.IntegerField()),
                ('duration_days', models.IntegerField()),
                ('dose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt_app.dose')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt_app.prescription')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt_app.prescription')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt_app.test')),
            ],
        ),
    ]
