# Generated by Django 5.0.6 on 2025-01-03 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt_app', '0005_prescriptionmedicine_prescriptiontest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptiontest',
            old_name='Prescription',
            new_name='prescription',
        ),
    ]
