# Generated by Django 5.0.6 on 2025-01-03 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt_app', '0006_rename_prescription_prescriptiontest_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionmedicine',
            name='dose',
        ),
        migrations.AddField(
            model_name='prescriptionmedicine',
            name='medicine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic_mgt_app.medicine'),
            preserve_default=False,
        ),
    ]
