# Generated by Django 5.1.2 on 2025-01-15 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_mgt_app', '0008_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Receptionist'), (3, 'Doctor'), (4, 'Patient'), (5, 'Pharmacist')], null=True),
        ),
        migrations.CreateModel(
            name='Pharmacistprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('pharmacy_name', models.CharField(max_length=100)),
                ('emergency_contact', models.CharField(blank=True, max_length=15)),
                ('phar_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
